version: "3.3"
services:
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'default'
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
  app:
    build: ./php8
    ports:
      - "9000:9000"
    volumes:
    - ../:/var/www
  web:
    image: nginx
    ports:
      - "80:80"
      - "8081:8081"
    volumes:
      - ../:/var/www
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
  gui:
    build: ./gui
    ports:
      - "8080:8080"
    volumes:
      - ../:/var/www
